module DrawOptionsShowFix where
import Abstract(Name(..))
import Fixity

-- These types are the same as the ones defined in DrawOptions but without
-- labelled fields, since the derived Read instances generated by hbc
-- can't read the strings produced by the derived Show instances for such
-- types.

data GlobalArgOptions
  = GlobalArgOptions
	              Bool          -- argument hiding on/off
                        [(Name,ArgOptions)]
	 
  deriving (Show,Read)

data ArgOptions
  = ArgOptions
	             Int 	-- number of hidden arguments
	             Fixity
		     (Maybe String)
		     Bool
	       -- more...
	 
  deriving (Show,Read)
